language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
sudo: false
before_script:
  - "npm install mocha"
  - "npm install istanbul"
script: "npm run-script test-ci"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
