language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.5"
sudo: false
before_script: "npm install mocha@2.2.4"
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"
