environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install mocha
  - npm install istanbul
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-ci
version: "{build}"
